# Generated by Django 3.0.1 on 2020-01-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
