# Generated by Django 3.0.1 on 2019-12-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('github_link', models.CharField(max_length=200)),
                ('live_link', models.CharField(max_length=200)),
            ],
        ),
    ]
